[project]
name = "weibo"
version = "0.1.0"
description = "Default template for PDM package"
authors = [{ name = "ARCTURUS", email = "ice99125@qq.com" }]
dependencies = ["requests>=2.32.5"]
requires-python = "==3.13.*"
readme = "README.md"
license = { text = "MIT" }


[tool.pdm]
distribution = false
